name: Generate and Send Lighthouse Report (JSON)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Lighthouse
        run: npm install -g lighthouse

      - name: Run Lighthouse and generate JSON report
        run: |
          echo "Collecting Lighthouse data..."
          lighthouse https://example.com --output json --output-path ./lighthouse-report.json --chrome-flags="--headless"

      - name: Send Lighthouse Report to Backend
        run: |
           curl -X POST -H "Content-Type: application/json" -d @lighthouse-report.json http://localhost:3000/api/lighthouse-report

      - name: Upload Lighthouse Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: lighthouse-report.json